### ISSUE TITLE
Last Version Return Bad Request - 400

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [pacification/fastlane-plugin-diawi#19]
+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | assembleDebug    | 511         |
| 💥   | diawi            | 3           |
+------+------------------+-------------+

[13:46:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distribute to hockeyapp suddenly failing
    https://github.com/fastlane/fastlane/issues/400 [closed] 8 💬
    22 Sep 2016

➡️  iOS provisioning profile auto-repair throwing `400 Bad Request` on `match` after running `produce enable_services`
    https://github.com/fastlane/fastlane/issues/17116 [closed] 3 💬
    02 Nov 2020

➡️  400 Bad request
    https://github.com/fastlane/fastlane/issues/15587 [closed] 3 💬
    13 Feb 2020

and 32 more at: https://github.com/fastlane/fastlane/search?q=400%20Bad%20Request&type=Issues&utf8=✓

bundler: failed to load command: fastlane (/home/circleci/.rubies/ruby-2.6.1/bin/fastlane)
Traceback (most recent call last):
	50: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `<main>'
	49: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `load'
	48: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	47: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	46: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	45: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	44: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	43: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	42: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	41: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	38: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	37: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	36: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	35: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `load'
	33: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
	32: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	31: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	30: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	29: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	28: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	27: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	26: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	25: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	24: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	23: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:58:in `block (2 levels) in parsing_binding'
	16: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-plugin-diawi-2.1.0/lib/fastlane/plugin/diawi/actions/diawi_action.rb:47:in `run'
	 8: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
	 7: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 3: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)
	50: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `<main>'
	49: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `load'
	48: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	47: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	46: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	45: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	44: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	43: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	42: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	41: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	38: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	37: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	36: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	35: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `load'
	33: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
	32: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	31: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	30: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	29: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	28: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	27: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	26: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	25: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	24: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	23: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:58:in `block (2 levels) in parsing_binding'
	16: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-plugin-diawi-2.1.0/lib/fastlane/plugin/diawi/actions/diawi_action.rb:47:in `run'
	 8: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
	 7: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 3: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)

Exited with code exit status 1
CircleCI received exit code 1

**Comment by mariofelesdossantosjunior** [comment]
My apk limit size
